### ISSUE TITLE
Move "microprofile-config.properties" to "src/main/resources/META-INF/microprofile-config.properties"

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/guides-common#1035]

**Comment by gkwan-ibm** [comment]
will investigate the following guides:
 - guide-mongodb-intro
 - guide-liberty-deep-dive-gradle 
   - will be fixed by https://github.com/OpenLiberty/guide-liberty-deep-dive-gradle/issues/19
 - guide-microprofile-jwt
 - guide-microprofile-openapi
 - guide-microprofile-telemetry-jaeger
 - guide-microprofile-rest-client
 - guide-containerize
 - guide-graphql-client
 - guide-jpa-intro
 - guide-containerize-podman
 - guide-liberty-deep-dive
   - will be fixed by https://github.com/OpenLiberty/guide-liberty-deep-dive/pull/230

**Comment by gkwan-ibm** [comment]
- move `src/main/webapp/META-INF/microprofile-config.properties` to `src/main/resources/META-INF/microprofile-config.properties` under the finish and start directories
- update the README.adoc if necessary

**Comment by gkwan-ibm** [comment]
close
- the guides were updated
