### ISSUE TITLE
Create an Intro to MicroProfile document

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/guides-common#107]
Create an Introduction to MicroProfile guide.

* Introduce new users to MP
* Summarize the capabilities and purposes of MP features
* Serve as an introduction to the other MP guides
* Become (hopefully) the definitive intro to MP, which will draw people to ol.io.
* Link to it from as many places as possible

**Comment by cajaygle** [comment]
The MicroProfile lab for the Think conference provides a lot of good starting material for this guide.  

The getting started sample used on the ol.io homepage could be the basis for a sample app for the guide, since it already demonstrates three MP features.  If we did use this sample we may want to fork it and tweak the app's UI to better serve as an intro to MP.

**Comment by lauracowen** [comment]
I'm not sure about this as a guide. This sounds more like a blog post (or some form of 'static' page like the About page or in the Docs? so that it's 'cornerstone' SEO content that's linked to from everywhere, as you suggest) but not a hands-on guide as we already have a whole load of those on MP.

I agree we could/should have some sort of article/post which would give a clear introduction, reasons why the reader should try MP technologies, etc, and summarise/list the capabilities of MP with a link out to the relevant guides for each capability. I'm not sure of the benefit of writing a generic intro to MP guide because what would it cover in terms of technology? Either it would just point the reader to the Maven MP archetype but wouldn't be space to explain it all, or it would have to pick a couple of bits of MP but we already have guides that do that.

This guide: https://openliberty.io/guides/microprofile-intro.html was intended to be an intro to MP guide. I reviewed it, though, and it was really hard to see its point. What it turned out to be about was injecting dependencies and scoping applications, which was far more meaningful. That's why we decided to replace that guide with the Injecting Dependencies guide (https://openliberty.io/guides/cdi-intro.html) which covers much the same material, I think, but in a more focused and meaningful way.

I appreciate people might ask "what is MP?" and want an explanation about why they should try using its capabilities when writing microservices/apps, but MP isn't really 'a thing' - it's a collection of capabilities, in the same way as Java EE 7 is. So, in sum, I think this is a requirement for an article, not a guide. I'm happy to work on it with relevant people.

(BTW, Do you mean this lab of @gcharters ? https://github.ibm.com/CHARTERS/cloudnativejava-mp-gettingstarted)

**Comment by lauracowen** [comment]
Following on from my update above...I've just read through the lab I think you meant (by Kevin Sutter?) and I think that moreorless does what I said above (sorry, I hadn't seen it before). I'm discussing with Kevin about publishing it (or part of it) as a blog post at the moment. I think we could do that in the short term (eg this week) and then turn it into an introductory doc (I still don't think it's a guide, though, more an introductory article to the guides??) in the Docs section. I'd then edit the blog post to include only the time-specific stuff (eg news on v1.3) and point to the Docs for the more static stuff (eg pointers to each of the guides).

**Comment by yeekangc** [comment]
@lauracowen, yes, the Lab that Jay referenced is the one by Kevin, which is what you looked at recently.

Yes, this wouldn't be the usual guide or a guide by definition.  More an intro piece (for a category of guides) that would introduce the topic and guide you in working through the relevant set of guides.  So, a special kind of guide or an index of sort.

The thinking is that we will introduce categories to help organize the guides and for each category, there can be an introductory 'guide' to help users to understand and work through things.  Simpler form of tracks.

**Comment by lauracowen** [comment]
This is a similar approach to what I concluded we needed on WASdev.net some moons ago - have a category with intro text/summary and then links off to the more detailed material. We never got to do it on WASdev.net (we just have categories but no intro text to put them in context or to help the SEO of the category concepts) but I still really like the idea. So it'd be good to do that here.

**Comment by cajaygle** [comment]
I agree this wouldn't be your typical guide.  The benefit of doing it as a guide is that we already have this form of documentation and it would fit very well as the first thing in a category of guides.  If we introduce some new type of intro document then we'd want it to be it's own page/URL for SEO purposes.  We'd have to design it -- how it appears on other pages, and how the page itself looks -- and we'd have to develop a process for publishing such pages to the site.  That intro wouldn't have any sample code associated with it.  Instead of doing all that, why not use the guide format which already has all that infrastructure in place?

**Comment by lauracowen** [comment]
I think it depends what you mean by 'guide'.

I don't think these intros should have sample code associated with them (or, if there is some code it's just for illustration and not for copying and following along in a hands-on way). That's why I said it's not a guide - conceptually a guide is the combination of the text and sample code with the repository of code containing the finished and partly-finished sample (so that users can see the sample app running and learn how it works and adapt it for their own purposes).

If you just mean, at an implementation level, having a doc format that can be included in the All Guides categories (specifically as the first guide, I guess?), I agree (though I still don't think we should refer to it as a 'guide' so that we stay clear about what a guide is and not overload the term).

In terms of design, I agree (IIRC - I can't find the static guide designs at the moment) that these intro articles could look much like the guides (the navigation column and the main body column, just not the sync'd code column).

I wasn't sure what you meant by it needing its own page/URL for SEO purposes. If you mean the `/guides/` sub-directory in the guide page URLs (eg `https://openliberty.io/guides/microprofile-openapi.html`), I think it's fine going under that as these intros would be intros to the guides.

**Comment by cajaygle** [comment]
Regarding URL/SEO, I meant that the Intro doc should have an SEO-able URL, such as https://openliberty.io/guides/intro-to-microprofile.html    I agree that putting it under /guides make sense.

**Comment by cajaygle** [comment]
During discussion of this issue on 4/12 we agreed:

* An introductory document for a guides category would not be a guide itself, but a separate introductory document type.  The intro document would not have sample code associated with it, although it may have code snippets within the text.  TBD whether this document would need to live in its own repo.
* The intro document will appear as the first entry in the guide category and will be styled slightly differently from the guides to call it out as an intro.
* Work for the design of the intro doc and how it will appear is being tracked by #112 
* Work for how intro documents will be published to the site is being tracked by https://github.com/OpenLiberty/openliberty.io/issues/295
* This issue will be used to track the writing of the MP Intro content

**Comment by lauracowen** [comment]
Here's a draft that Kevin has on his list to review: https://openlibertydev.mybluemix.net/2018/04/24/java-microservices-microprofile.html

Any feedback from anyone is welcome. It's currently in blog form but if you have feedback relating to how it would be in the category intro context, please let me know too.

**Comment by cajaygle** [comment]
Hi Laura, some comments:
- I suggest not organizing the MP features by release, but rather in some logical way that will appeal to the MP newbie since this is an intro document.  For instance, in the current draft, the Metrics paragraph refers to Health Check before HC has been introduced.
- @megmulsy can create new diagrams, instead of the current Powerpoint versions
- Would it be useful to link to our MP API Javadoc?  Once, or specific links for each feature?
- When we link to our guides it might be nice to use the Guides card visual instead of a text hyperlink.  @megmulsy please look at this
- At the end of the intro doc we should link back to the MP Guides category, perhaps with a graphic.  useful for people who get to this doc via search instead of navigating through the site.

Some specific wording comments:
- In the first paragraph of the doc, "Eclipse MicroProfile is a set of vendor-neutral Java extensions..." it would be useful to include the word "open" somewhere in addition to saying vendor-neutral
- "The project has released three updates" -- suggest saying three "releases" instead of three "updates".  "Updates" sounds like a lesser deliverable.  "contains a full implementation of MicroProfile 1.3." -> "contains a full implementation of MicroProfile 1.3, which is the latest release."
- In the Metrics section, "Again, this is a popular feature with..."    remove "Again"
- In the JWT section, "are running on other vendors’ implementations."  Suggest changing "other" to "multiple".  
- In Open Tracing, there's a typo:  ashttps://zipkin.io/[Zipkin]

**Comment by cajaygle** [comment]
@lauracowen can you add a link to the latest draft here, thanks.

**Comment by kinueng** [comment]
Hi, I just happened to stumble by this issue.  @cajaygle here is the latest version of the blog post.
https://openlibertydev.mybluemix.net/blog/2018/06/08/java-microservices-microprofile.html

**Comment by lauracowen** [comment]
Oh! I'm sorry, Jay, I forgot I had all your feedback above to integrate before I published the blog post (Kevin finally reviewed it so I had his comments and I forgot you'd already sent these way back). It's published here: https://openliberty.io/blog/2018/06/08/java-microservices-microprofile.html

I agree with all the comments above (I did fix the Zipkin link) so they need to be integrated when we modify the post content for the MP intro page (at which point, I'll modify the blog post to redirect to the new page so we don't have both similar sets of content live).

**Comment by gcharters** [comment]
@cajaygle - what are the plans to create an official MP Intro?  I took a look at the blog post and in some respects, it's similar to the tutorial repo README - https://github.com/OpenLiberty/tutorial-microprofile .  It would be nice to have just one intro that introduced all the guides and could also be used in workshops.  At the moment, we're maintaining multiple things that serve very similar purposes (i.e. introduce MP and link to the guides).  We also have a requirement to provide an MP landing page for IBM Code and I'd like it to be this.

**Comment by yeekangc** [comment]
@gcharters, what's your take on this?  Is a guide of sort on OL.io what is best for this?  Or, you are thinking we can stick to what is in the tutorial repo?

**Comment by cajaygle** [comment]
This would appear on the guides page as the first tile in the Microprofile category.

**Comment by yeekangc** [comment]
Yes, it will appear as a tile but a different looking tile as part of a category, @gcharters.

**Comment by yeekangc** [comment]
Updating the title to better reflect what we want to do here.  This is not a "guide" by definition.

**Comment by proubatsis** [comment]
@gcharters I worked with @lauracowen and another iteration of the content is ready. Please review when you have the chance.

**Comment by kwsutter** [comment]
@proubatsis Comments...
o  In the opening paragraph, provide a hotlink to the OL Guides page.  Even if they make it no further than the first paragraph, they might venture over the Guides and we can catch their interest there.

o  Under "Microservices Architecture", there is this sentence:  

> "Another benefit is that failures in one service do not affect the entire system; if a service fails, other services that are independent of that service are not affected."   

But, shouldn't all services be independent and, thus, none of the other services should be affected?

o  I guess the next paragraph attempts to discuss how not all microservices can be independent, but are we diving into the exception path for an introductory article?  I mean this paragraph just gets you thinking about all of the various exceptions where microservices can't be independent (or not to the extent you might like).  This might be a great lead-in for fault tolerance processing.  I just don't know if I would dive into the exceptions so early in this introduction...  

o  Hate to say the MP is a set of "industry standard technologies" since we're not a Standards body.  We develop Specifications, but we're not Standards.  Maybe you should just say that "MP is a set of industry specifications..."

o  I would indicate that MP extends a small set of Java EE features...  not that it is based on the Java EE features.  This is to demonstrate that we complement Java EE, not replace it.

o  I would skip the reference to Spring...

o  Not sure what you are getting at with this statement, 

> "The JAX-RS APIs could be used to create JSON-RPC, or XML-RPC APIs"

o  The OpenAPI specification needs a hotlink to help differentiate from the MP OpenAPI specification.

o  "..natively produce OpenAPI documents from your JAX-RS applications." (not "their")

Otherwise, looks good!  Thanks.

**Comment by kinueng** [comment]
We have published the MicroProfile documentation here
https://openliberty.io/docs/intro/microprofile.html

**Comment by yeekangc** [comment]
As indicated above, this was done.  The decision was to do this as an intro article as part of our documentation.
