### ISSUE TITLE
Add an attribution to bottom of guides

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/guides-common#108]
We should add an attribution to the bottom of the asciidoc for the guides that points back to openliberty.io. The attribution clause is there to help anyone that 'forks' this onto their own site to comply with the CC license the asciidoc is using. It also means if someone else decides to host this they point it back to our hosted version which should help our google rank.

**Comment by sishida** [comment]
Do we want this information to be part of the guide itself, such as how "Contribute to this guide" and "Related guides" are their own sections, or is this information like the "fine print" that appears in the "License" and "Privacy policy" links at the bottom of all of the openliberty.io website pages?

**Comment by sishida** [comment]
Do we want this information to be part of the guide itself, such as how "Contribute to this guide" and "Related guides" are their own sections, or is this information like the "fine print" that appears in the "License" and "Privacy policy" links at the bottom of all of the openliberty.io website pages?

**Comment by sishida** [comment]
What if we added this info to either the "Great work! You're done!", "Contribute to this guide", or "Related guides" sections? I don't want to pad these sections with too much info, but we also don't want all of the guides to have a bunch of end material, either.

Maybe a statement that prompts the reader to comply with the CC license, such as, "If you would like to share this guide, link back to the source at <link>openliberty.io</link>."

Also, since this statement involves license compliance, maybe we should ask someone in legal for advice/review? I don't know if we need to include specific legal terms for an attribution statement like this.

**Comment by yeekangc** [comment]
This may be helpful:  https://wiki.creativecommons.org/wiki/Best_practices_for_attribution

**Comment by cajaygle** [comment]
“[Adding health reports to microservices](https://openliberty.io/guides/microprofile-health.html)” by [yeekangc](https://github.com/yeekangc) is licensed under [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)

**Comment by justineechen** [comment]
All guide attributions are updated on the published multipane site.
