### ISSUE TITLE
Guide for mongoDB

### ISSUE THREAD

**Issue by mswatosh** [OpenLiberty/guides-common#148]
With the changes to how we are handling future versions of mongoDB, we'll need a guide to help users with newer versions.

Draft outline:
- Title
- What you will learn
- Getting Started
  - Mongo Setup
     - Use Existing
     - Docker install
     - Install from mongo
  - No need for a mongo feature!
- Creating a Mongo Producer
- Basic CRUD operations
- Using an encoded password with passwordUtilities-1.0
- Using SSL
- Great work! You're done!

**Comment by gcharters** [comment]
The outline is likely to be different as we tend to be concise and wouldn't got into historical info.

**Comment by mswatosh** [comment]
@gcharters If you're referring to the 'Changes from mongo-2.0 feature', I think we'll need a section in the guide to make it clear that enabling a mongo feature is no longer the way to use mongoDB. I'd like to get ahead of the inevitable confusion that the existence of a mongo-2.0 feature but not mongo-3.0 or mongo-4.0 feature will cause.

**Comment by mswatosh** [comment]
Closing in favor of doing a blog post instead

**Comment by yeekangc** [comment]
We may still want to do a guide on MongoDB.  Not specific to any particular feature version.

**Comment by yeekangc** [comment]
This guide is not meant to cover the mongo feature but to take users through getting going with MongoDB for their microservices running on Open Liberty.

**Comment by yeekangc** [comment]
Reference materials: https://openliberty.io/blog/2019/02/19/mongodb-with-open-liberty.html

**Comment by yeekangc** [comment]
@jimmy1wu and Benson (Ning) are looking at this.

Jimmy, I don't have Benson's ID.  Feel free to tag him directly.

**Comment by jimmy1wu** [comment]
@yeekangc i think he's still waiting to be added to the openliberty org.

**Comment by yeekangc** [comment]
No problem and thank you, @jimmy1wu.

**Comment by evelinec** [comment]
- fixing hotspot issues on staging site

**Comment by ankitagrawa** [comment]
Addressing dev content review feedback

**Comment by ankitagrawa** [comment]
Ready for peer review
- Mac : Darren
- Linux : Ankit
- Windows : Darren

**Comment by ankitagrawa** [comment]
- addressing Trevors feedback.
- TravisScript in progress.

**Comment by gkwan-ibm** [comment]
- addressing Trevors feedback.
  - fixed the TravisScript and will check the result on tomorrow

**Comment by gkwan-ibm** [comment]
- still addressing the Win issue

**Comment by gkwan-ibm** [comment]
- changing the content to use new Dockerfile approach to create the .pem and .p12 files

**Comment by gkwan-ibm** [comment]
- approved the new Dockerfile approach works on all 3 platforms

**Comment by gkwan-ibm** [comment]
- ready for dev content review soon

**Comment by ankitagrawa** [comment]
Ready for Gilbert to review.

**Comment by gkwan-ibm** [comment]
- dev content review 4 https://github.com/OpenLiberty/draft-guide-mongodb/issues/14

**Comment by gkwan-ibm** [comment]
- addressing the dev content review 4 feedback

**Comment by ankitagrawa** [comment]
- addressed the feedback.
- ready for review.

**Comment by gkwan-ibm** [comment]
- dev content review 5
  - https://github.com/OpenLiberty/draft-guide-mongodb/issues/15

**Comment by gkwan-ibm** [comment]
- addressed the dev content review 5

**Comment by gkwan-ibm** [comment]
- revising the readme
- trying to use jdk image to build the mongodb image instead of using OL image

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
- dev content review 6
  - https://github.com/OpenLiberty/draft-guide-mongodb/issues/19

**Comment by gkwan-ibm** [comment]
- addressing dev content review 6

**Comment by gkwan-ibm** [comment]
- ready for review

**Comment by gkwan-ibm** [comment]
- addressing dev content review feedback

**Comment by gkwan-ibm** [comment]
- ready for review

**Comment by gkwan-ibm** [comment]
- next peer review
  - Mac (Ankit)
  - Linux (Nimrah)
   - Win (Danny)

**Comment by gkwan-ibm** [comment]
- confirm the fixes
- next is SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- addressing SME feedback

**Comment by gkwan-ibm** [comment]
- SME review completed
- next user review

**Comment by gkwan-ibm** [comment]
- user view completed
- next final content review after GK review

**Comment by gkwan-ibm** [comment]
- addressing stakeholder feedback

**Comment by gkwan-ibm** [comment]
- addressed the feedback and ready for review

**Comment by yeekangc** [comment]
Signing off assuming @lauracowen is good with the latest version too.  Cc @Charlotte-Holt.

Team, thank you for getting us to where we are.

**Comment by lauracowen** [comment]
I'm fine except for a couple of structural points (I don’t think there’s any reason why they would need to be different from the other guides):

- Could the info in the “setting up MongoDB” be moved to be part of the otherwise sparse “Additional prerequisites” section? It relates to the Docker installation bit mentioned there (and would provide more context as to why you're needing to install Docker anyway) and you have to do it before you can do anything else (so it's a prereq in that sense). Then the “Try what you’ll build” sub-section can be part of “Getting Started” like it normally is in the other guides. I’m not comfortable with changing the standard structure when I don’t think it needs to be. Also, moving the mongodb setup to Additional prerequisites reduces the number of additional sections/length.
- Can the heading “Defining the MongoDB information” use the normal “Configuring…” term instead? I know it’s more than configuring the server here but “Configuring the MongoDB driver and the server” would work and would be more recognisable if you've previously used other guides. I wasn’t sure what to expect in a section called “Defining….” and was like “oh, configuring” when I read it.

The other, minor, thing that I wondered (maybe a question for Gilbert/YK re SEO) should “a document-oriented database.” be “a document-oriented noSQL database.” or similar? (I don’t know - it’s just that noSQL is a term that’s easily recognisable and I don’t think we mention it anywhere. I don’t know whether these instructions could be adapted easily for other noSQL databases eg if someone is searching for noSQL instructions and comes across these?)

**Comment by yeekangc** [comment]
+1 for "NoSQL".  @meswan, please consider.

I was wondering about "Defining the MongoDB info ..." too.  Thank you, Laura!

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/mongodb-intro.html
