### ISSUE TITLE
Improve design for presenting platform-specific content

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#179]
We have user test feedback on the Kubenetes guide that uses the system separation design, the separation is not clear enough, ie, the indentation is not obvious. Can you consider making an improvement? 

User test feedback: 
But my confusion with this part of the guide was that I couldn't tell when the LINUX instructions ended and the overall instructions began. So is it possible to section off the instructions that depend on environment even more? Maybe in a box or have a beginning line / end line in gray?

**Comment by yeekangc** [comment]
@kinueng

**Comment by mdenby** [comment]
Here are the tabs for the operating systems--both desktop and mobile. I didn't show the prerequisites on the right panel because Jay is having me visually style them. 

<img width="440" alt="Screen Shot 2019-04-02 at 9 48 42 AM" src="https://user-images.githubusercontent.com/26823018/55410681-46704780-5532-11e9-9ce8-091e49d99189.png">
<img width="325" alt="Screen Shot 2019-04-02 at 9 48 54 AM" src="https://user-images.githubusercontent.com/26823018/55410682-4708de00-5532-11e9-9e69-d2827c835dd0.png">

**Comment by gkwan-ibm** [comment]
Fixed by UI
