### ISSUE TITLE
Guide for deploying Open Liberty to the IBM Cloud

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guides-common#181]
Our competitors have guides for deploying to different clouds so I thought we should be doing the same. Strategically we should create one for the IBM cloud first. This could be done using containers and Kubernetes.

**Comment by yeekangc** [comment]
We will focus on containers and cover both IBM Cloud public and private.

**Comment by evelinec** [comment]
- can start with ICP

**Comment by gkwan-ibm** [comment]
- wrote down the instruction for ICP
- looking at IBM public cloud

**Comment by gkwan-ibm** [comment]
- ICP guide is drafted
- working on IBM Public Cloud

**Comment by gkwan-ibm** [comment]
- ICP/Public cloud guide will be completed the draft soon

**Comment by gkwan-ibm** [comment]
- draft is ready
- YK is reviewing and addressing his feedback

**Comment by gkwan-ibm** [comment]
- working on YK feedback
- converting to multipane

**Comment by evelinec** [comment]
- should have PR ready for both YK feedback and multipane 
- after the PR, ready for peer review 
  - open ibm cloud account with a non-ibm email (7 days)
  - TBD

**Comment by evelinec** [comment]
- multipane conversion has a new defect for this guide
- pending on Laura and Jay's review on the guide's flow

**Comment by evelinec** [comment]
- still discussing the flow and content with team, pending on some reviews

**Comment by evelinec** [comment]
- make some update and continue to discuss

**Comment by evelinec** [comment]
- working on Laura's feedback and continue to discuss

**Comment by evelinec** [comment]
- new feedback to work on

**Comment by evelinec** [comment]
- work on the feedback today

**Comment by gkwan-ibm** [comment]
- target to do peer review in this week

**Comment by gkwan-ibm** [comment]
- Gilbert is reviewing

**Comment by gkwan-ibm** [comment]
- Gilbert reviewed
- addressed all Gilbert's feedback
- can start Peer review (Andrew)
  - Mac, Linux, Win
  - Java8, Java11
  - Treat as a new IBM cloud user
  - use the new checklist (https://github.com/OpenLiberty/draft-guides-template/issues/12)

**Comment by gkwan-ibm** [comment]
- will address YK's feedback

**Comment by gkwan-ibm** [comment]
- addressed YK's feedback
- Andrew is doing Peer review
  - completed Mac with Java8

**Comment by gkwan-ibm** [comment]
- trying to finish the peer review today

**Comment by gkwan-ibm** [comment]
- Peer review finished for all platforms
- fixing the peer review feedback
- Content review will be by YK, EC, or GK

**Comment by gkwan-ibm** [comment]
- making Travis work

**Comment by gkwan-ibm** [comment]
- enabled Travis test 
   - investigating the helm install failure

**Comment by evelinec** [comment]
- Content review will be by YK, EC, or GK

**Comment by gkwan-ibm** [comment]
- Will investigate why helm chart not work on miniKube
- will contact SC for SME reviewer

**Comment by gkwan-ibm** [comment]
- changed the idea to not using helm chat

**Comment by gkwan-ibm** [comment]
- after the discussed in slack, IBM Cloud guide will use helm and not other clouds, but eventually the helm should be supported in running different clouds
- will do SME review

**Comment by gkwan-ibm** [comment]
- Will investigate the issue of applying helm chart to miniKube

**Comment by gkwan-ibm** [comment]
- SME (Leo and Steven) completed with minor feedback

**Comment by gkwan-ibm** [comment]
- working on SME feedback

**Comment by gkwan-ibm** [comment]
- PR will be ready for SME feedback on today
- will convert to use inventory and system microservices

**Comment by evelinec** [comment]
- waiting for Leo and Steven to review the SME PRs
- converted the app to use the inv ms, tested it, updating the readme

**Comment by gkwan-ibm** [comment]
- Leo feedback done
- waiting Steven feedback
- working on the conversion

**Comment by gkwan-ibm** [comment]
- created PR for Steven feedback
- Acrolink check completed
- TW will do the user review

**Comment by gkwan-ibm** [comment]
- fixing the automation test

**Comment by gkwan-ibm** [comment]
- merge the existing PRs first, so that TW can start the user review
- then fix the automation problem

**Comment by gkwan-ibm** [comment]
- Inventory/system conversion PR is under reviewing
  - TW will start the user review when the PR is merged
- automation issue was fixed

**Comment by gkwan-ibm** [comment]
- scrub the feedback issues

**Comment by gkwan-ibm** [comment]
- PR for GK feedback is ready for review

**Comment by gkwan-ibm** [comment]
- User reviewing

**Comment by evelinec** [comment]
- Tommy can finish user review today

**Comment by gkwan-ibm** [comment]
- addressing User review feedback and target on today
- there is an issue for the copy icon in single pane

**Comment by gkwan-ibm** [comment]
- addressing YK feedback

**Comment by evelinec** [comment]
@Charlotte-Holt This guide is ready for you to review. Here's the repo: https://github.com/OpenLiberty/draft-guide-cloud-ibm

**Comment by evelinec** [comment]
Expected ID edits by EOD, 5/20.

**Comment by dmuelle** [comment]
Here are my suggested edits by section. Let me know if you have any questions. Thanks!

### WHAT YOU’LL LEARN

**Change:**
Various clouds offer solutions for running your workloads in a Kubernetes cluster. Using a cloud-based infrastructure allows you to focus on developing your microservices rather than worrying about details that are related to the servers you deploy them to. Using a cloud allows you to easily scale your microservices and serve them in a high-availability setup.

**To**
There are different cloud-based solutions for running your workloads in a Kubernetes cluster. A cloud-based infrastructure enables you to focus on developing your microservices without worrying about the servers you deploy them to. Using a cloud helps you to easily scale and serve your microservices  in a high-availability setup.

**Change**
IBM Cloud offers a hosted Kubernetes service that is called IBM Cloud Kubernetes Service (IKS). IKS is a service that is offered as part of IBM’s public cloud offerings. It provides a hosted Kubernetes cluster that you can deploy your microservices to. You will use it in conjunction with IBM Cloud Container Registry. IBM Cloud Container Registry is a private registry that is used to store and distribute your container images.

**To**
IBM Cloud Kubernetes Service (IKS) is part of IBM’s public cloud offerings. It provides a hosted Kubernetes cluster where you can deploy your microservices. Use it with IBM Cloud Container Registry, a private registry used to store and distribute your container images.

**Change**
The system microservice returns the JVM system properties of the running container and it returns the pod’s name in the HTTP header making replicas easy to distinguish from each other. 
**To**
The system microservice returns the Java virtual machine (JVM) system properties of the running container. It also returns the pod’s name in the HTTP header, making replicas easy to distinguish from each other. 

**Change**
You will use Helm to deploy these microservices to IBM Cloud using Open Liberty Helm charts. Helm is a package manager for Kubernetes. It uses templates to generate Kubernetes yaml files and then deploys and manages them as releases in your cluster.
**To**
You will use Open Liberty Helm charts to deploy these microservices to IBM Cloud. Helm is a package manager for Kubernetes. It uses templates to generate Kubernetes yaml files and then deploys and manages them as releases in your cluster.

### CREATING A KUBERNETES CLUSTER ON IBM CLOUD

**Change**
Running this script installs several tools that are useful for interacting with IBM Cloud. It installs the ibmcloud, kubectl, helm, and curl tools, which are needed to complete this guide
**To**
Running this script installs several tools that are useful for interacting with IBM Cloud, including the ibmcloud, kubectl, helm, and curl tools, which are needed to complete this guide.

**Change**
When you are prompted to select a region, choose us-south. Creating a free cluster is limited to specific regions, choosing us-south allows you to create a free cluster.
**To**
When you are prompted to select a region, choose us-south. This allows you to create a free cluster, which is limited to specific regions.

**Change**
Follow the instructions that are given on the prompt and in your web browser to complete the login process.
**To**
Follow the instructions in the prompt and in your web browser to complete the login process.

**Change**
To create a Kubernetes cluster, you need appropriate permission. Ensure that you have Administrator access to IBM Cloud Kubernetes Service. Navigate to the IBM Cloud Dashboard. Then navigate to Manage > Access (IAM) > Users > [Your Username] > Access Policies and ensure that Administrator is listed as a policy for all resources in the account or for the Kubernetes service.
**To**
To create a Kubernetes cluster, you need Administrator access to IBM Cloud Kubernetes Service.  To confirm that you have Administrator access, navigate to the IBM Cloud Dashboard. Then, navigate to Manage > Access (IAM) > Users > [Your Username] > Access Policies and confirm that `Administrator` is listed as a policy for all resources in the account or for the Kubernetes service.

### DEPLOYING MICROSERVICES TO IBM CLOUD KUBERNETES SERVICE(IKS)

**Change**
You will build and containerize the system and inventory microservices, push them to a container registry and then deploy them to your Kubernetes cluster.
**To**
You will build and containerize the system and inventory microservices, push them to a container registry, and then deploy them to your Kubernetes cluster.

**Change**
The first step of deploying to Kubernetes is to build your microservices and containerize them.
**To**
The first step of deploying to Kubernetes is to build and containerize your microservices.

**Change**
We’ve setup the projects such that this process is automated as a part of a single Maven build
**To**
We’ve set up the projects such that this process is automated as a part of a single Maven build.

**Change**
The plug-in automatically picks up the Dockerfile located in the same directory as its POM file and builds a Docker image from it.
**To**
The plug-in automatically picks up the Dockerfile that is located in the same directory as its POM file and builds a Docker image from it.

**Change**
This goal builds a Docker image from the Dockerfile located in the same directory as the POM file.
**To**
This goal builds a Docker image from the Dockerfile that is located in the same directory as the POM file.

**Change**
Pushing the images to a registry allow the cluster to create pods using your container images.
**To**
Pushing the images to a registry enables the cluster to create pods by using your container images.

**Change**
The container registry plugin was installed automatically while running the idt-installer earlier in this guide. Use the container registry plugin to create a namespace for your container images.
**To**
The container registry plug-in was installed automatically when you ran the idt-installer earlier in this guide (see “Installing command-line tools for IBM Cloud”). Use the container registry plug-in to create a namespace for your container images.

**Change**
Use the plugin again to login to the container registry.
**To**
Use the plug-in again to log in to the container registry.

**Change**
Next, you need to tag your container images with the relevant data about your registry. Remember to substitute [your-namespace] for the namespace you previously created.
**To**
Next, tag your container images with the relevant data about your registry. Remember to replace [your-namespace] with the namespace you created earlier in the guide.

**Change**
Finally, push your images to the registry. Remember to substitute [your-namespace] for the namespace you previously created
**To**
Finally, push your images to the registry. Remember to replace [your-namespace] with the namespace you created earlier in the guide.

**Change**
Use Helm to deploy the system microservice. Remember to substitute [your-namespace] for the namespace you created earlier in the guide.
**To**
Use Helm to deploy the system microservice. Remember to replace [your-namespace] with the namespace you created earlier in the guide.

**Change**
Use Helm to deploy the inventory microservice. Remember to substitute [your-namespace] for the namespace you created earlier in the guide.
**To**
Use Helm to deploy the inventory microservice. Remember to replace [your-namespace] with the namespace you created earlier in the guide.

**Change**
After running helm install, an output will be displayed providing instructions on how to access your deployed microservices.
**To**
After you run the helm install, an output is displayed providing instructions on how to access your deployed microservices.

### DEPLOYING A NEW VERSION OF A SYSTEM MICROSERVICE
**Change**
You can re-deploy a microservice using Helm to upgrade the release.
**To**
You can redeploy a microservice by using Helm to upgrade the release.

**Change**
Use the following command to find the name of the pod running the system microservice.
**To**
Use the following command to find the name of the pod that is running the system microservice.

### TEARING DOWN THE ENIVRONMENT
**Change**
Logout of your container registry.
**To**
Log out of your container registry.

**Change**
Logout of the ibmcloud command line tool.
**To**
Log out of the ibmcloud command-line tool.

### DEPLOYING TO IBM CLOUD PRIVATE
**Change**
Some situations may require you to manage your own infrastructure, such as if you want to deploy on-premises. If this describes your needs, then private clouds may be a more suitable solution for you.
A private cloud may be a more attractive option to those who must run their services on infrastructure that is controlled by them. While the operations team will still need to maintain this infrastructure, a private cloud still provides benefit to developers so they don’t need to think about infrastructure.
**To**
A private cloud is a good option for developers who want to run their microservices on an infrastructure that they control. While the operations team will still need to maintain this infrastructure, a private cloud saves developers from having to worry about infrastructure.

**Change**
Deploying microservices to ICP is a similar process as deploying to IKS. The main differences that you will notice are in the setup process and how you tag your container images.
**To**
Deploying microservices to ICP is similar to deploying to IKS. The main differences are in the setup process, and in how you tag your container images.

**Change**
To set up your local environment, from the ICP Dashboard navigate to the Command Line Tools > Cloud Private CLI page from the menu and follow the instructions to set up each CLI tool.
**To**
To set up your local environment, go to the ICP Dashboard. Navigate to the Command Line Tools > Cloud Private CLI page and follow the instructions to set up each CLI tool.

**Change**
This is because ICP has Helm’s Tiller setup for you out of the box.
**To**
This is because ICP has Helm’s Tiller set up out-of-the-box.

**Change**
This tag specifies mycluster.icp:8500 as the container registry to push to and it specifies default as the namespace your image’s repository will reside in.
**To**
This tag specifies mycluster.icp:8500 as the container registry to push to and default as the namespace that your image’s repository will reside in.

**Comment by andrewdes** [comment]
@dmuelle I have addressed your feedback and opened a PR for your review here: https://github.com/OpenLiberty/draft-guide-cloud-ibm/pull/32

**Comment by dmuelle** [comment]
@andrewdes just reviewed the PR- just a couple small fixes

**Comment by dmuelle** [comment]
@andrewdes looks good, changes approved &  I've added the ID reviewed label

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/cloud-ibm.html.
