### ISSUE TITLE
Publish the converted multipane guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#206]
- [x] publish
- [x] post publish test
- [x] update template
- [ ] update instruction
- [ ] update the Guidelines for Structure and Styles
   - https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles

**Comment by yeekangc** [comment]
How does relate to #177?

**Comment by gkwan-ibm** [comment]
#177 just do the conversion and make changes ready. When we sign off and the site is updated to multipane, this work can be started

**Comment by yeekangc** [comment]
If this should be tied under the epic i.e. #177, let us do that.  Thank you.

**Comment by evelinec** [comment]
- cleaning up the instructions

**Comment by evelinec** [comment]
- reviewing the Guidelines for Structure and Styles wiki that includes the multipane instructions
  - JC to request review from Steven
  - EC to review and test the instruction

**Comment by evelinec** [comment]
Review feedback on the Guidelines for Structure and Styles wiki: 

- [ ] Any files that are mentioned in hotspots or code commands should be included as a code column. => Any files that are mentioned in hotspots or code commands are included as a code column. (As the hotspots or code commands need to be added in order to show up on the code column.)

- [ ] Add "include" examples for these subsections: 
- Code command -> Create, Replace, and Update

- [ ] Syntax error: `#Replace this `filename` class#.` -> #Replace this `filename` class.# (2 occurrences)

- [ ] At the end of the "Hotspots" section, add subsection/example to show how to add hotspots with multiple files? 

- [ ] In the "Hotspots" section, backtick some syntax being used, ie, [hotspot], [hotspot=start-finish], [hotspot=start-finish hotspot=start-finish..]

- [ ] In the "Links" subsection, not sure what this sentence means: `localhost links that are meant to be clicked can remain in their original format`

- [ ] At the end of the "Links" subsection, add open in a new tab instruction?

- [ ] This guideline doc is now quite long. Not sure that'll discourage user from reading it. Altho I like to put all the relevant information in one place.

**Comment by justineechen** [comment]
Draft-guides-template:
- Add a table of contents 
- Add images to show what the results will look like for multipane

**Comment by evelinec** [comment]
- wiki update should be done soon, then can be reviewed

**Comment by evelinec** [comment]
New review feedback on the wiki: 

- [ ] The "Types of Guides" link in the TOC is not clickable

- [ ] I think the original sentence is clearer and sufficient. The modified sentences (below) is confusing, imo. 
"Any files that are mentioned in hotspots or code commands should be included as a code column in that subsection. The hotspots and code commands will not be pointed to anything if the code column "include" isn't put in the same subsection as these commands."
I meant to suggest to change the original sentence from "Any files that are mentioned in hotspots or code commands should be included as a code column." to "Any files that are mentioned in hotspots or code commands are included as a code column." 
The reason being the hotspots or code commands need to be added in order to show up on the code column, using "should be" didn't seem to fit.

- [ ] The "include::file" examples may be good to include the example full path, ie, src/main/...filename

Others look good.

**Comment by gkwan-ibm** [comment]
close this issue
for the above feedback will be addressed by https://github.com/OpenLiberty/guides-common/issues/258
