### ISSUE TITLE
MicroProfile guides inconsistencies with "mvn" commands

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/guides-common#212]
Under the 'Getting Started' section, certain MicroProfile guides have instructions to execute:
`mvn install liberty:start-server`
while others have instructions to execute:
`mvn clean install`
`mvn liberty:start-server`
or other various combinations of the above.

Perhaps certain guides should be edited to maintain consistency across all MicroProfile guides.

Guides indicating `mvn install liberty:start-server`:
https://openliberty.io/guides/cdi-intro.html
https://openliberty.io/guides/microprofile-rest-client.html
https://openliberty.io/guides/microprofile-openapi.html
https://openliberty.io/guides/microprofile-health.html
https://openliberty.io/guides/microprofile-metrics.html
https://openliberty.io/guides/microprofile-config.html

Guides indicating
`mvn install`
`mvn liberty:start-server`:
https://openliberty.io/guides/microprofile-opentracing.html

Guides indicating 
`mvn clean install`
`mvn liberty:start-server`:
https://openliberty.io/guides/rest-client-java.html
https://openliberty.io/guides/microprofile-jwt.html

Guides indicating `mvn clean install liberty:start-server`:
https://openliberty.io/guides/microprofile-fallback.html

**Comment by gkwan-ibm** [comment]
- remove `clean` if it is not necessary
- find out which guides is not using `mvn install liberty:start-server`
    - the guides can run `mvn install liberty:start-server`, fix it
     - otherwise leave it

**Comment by justineechen** [comment]
Guides that are not using `mvn install liberty:start-server`:
- https://openliberty.io/guides/microprofile-opentracing.html
  - https://github.com/OpenLiberty/guide-microprofile-opentracing/issues/58
  - fails with `mvn install liberty:start-server` mentioned in the issue above ^ 
- https://openliberty.io/guides/maven-intro.html
  - does not fail with `mvn install liberty:start-server` but is separated in order to describe to the reader exactly what these two commands accomplish, separately
  - this is included from : {common-includes}/mvnbuild.adoc[]
  - <img width="569" alt="Screen Shot 2019-03-11 at 3 28 14 PM" src="https://user-images.githubusercontent.com/18709242/54151908-50f75f80-4412-11e9-8f80-082cc4d6aeb5.png">
- https://openliberty.io/guides/rest-intro.html
  - same as maven-intro guide ^ 
- https://openliberty.io/guides/maven-multimodules.html
  - `mvn install` is ran in the `start` dir and `mvn liberty:start-server` is ran from `ear` dir 
  - no change 
- https://openliberty.io/guides/rest-hateoas.html
  - same as maven-intro and rest-intro guides ^

**Comment by justineechen** [comment]
Will update the following guides:

- [ ] https://openliberty.io/guides/maven-intro.html
- [ ] https://openliberty.io/guides/rest-intro.html
- [ ] https://openliberty.io/guides/rest-hateoas.html

**Comment by gkwan-ibm** [comment]
Most of the guides were addressed this issue during multipane conversion. 

Thanks Justine to find out those guides which are still using `mvn install` and `mvn liberty:start-server`. The separation in some guides is by purpose. I think following changes are not necessary:
- OpenLiberty/guide-rest-intro#68
- OpenLiberty/guide-maven-intro#48
- OpenLiberty/guide-rest-hateoas#41

I closed this issue.

@kathrynkodama if you have any other concern, would you reopen this issue or open a new issue? Thanks
