### ISSUE TITLE
Automation tests fails to grep openjdk11 in test log

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#217]
OpenLiberty release: 19.0.0.1
Open Liberty build number: wlp-1.0.24.cl190120190114-1900
Java version: 
The command "build=$(grep "Open Liberty" $logsPath/console.log | cut -d" " -f5 | cut -d")" -f1 ); release=$( echo "$build" | cut -d"/" -f1); number=$(echo "$build" | cut -d"/" -f2); ol_jv=$(grep -i "on java" $logsPath/console.log); jv=$(echo "$ol_jv" | sed "s/.* on //g"); echo -e "
"; echo -e "OpenLiberty release: $release"; echo -e "Open Liberty build number: $number"; echo -e "Java version: $jv";" exited with 0.

**Comment by evelinec** [comment]
Assigned to @andrewdes as he worked on finding the solution for this problem for some of the guides and automation. He'll fix for all the impacted guides.

**Comment by NimG98** [comment]
Change `grep -i "on java"` to `grep -i "version"`

**Comment by NimG98** [comment]
To be fixed:
- [ ] guide-microprofile-jwt
- [ ] guide-microprofile-opentracing
- [ ] guide-rest-hateoas
- [ ] guide-jpa-intro
- [ ] guide-maven-multimodules
- [ ] guide-cors
- [ ] guide-security-intro
- [ ] guide-gradle-intro
- [ ] guide-microprofile-rest-client-async
- [ ] draft-guide-jax-rs-reactive-client

Being fixed in devmode PR:
- [ ] guide-maven-intro
- [ ] guide-microprofile-config
- [ ] guide-microprofile-health
- [ ] guide-rest-client-java
- [ ] guide-microprofile-openapi

Being fixed in other PR:
- [ ] guide-cdi-intro
- [ ] guide-microprofile-fallback
- [ ] guide-microprofile-metrics
- [ ] guide-microprofile-rest-client

**Comment by gkwan-ibm** [comment]
put it to icebox. When decide to run daily build test against openjdk11, this issue will be resumed

**Comment by gkwan-ibm** [comment]
close
- daily build test is testing against jdk11
- the github action should work fine
- will open individual issue if the problem happens again
