### ISSUE TITLE
Reduce the SRVE9967W warnings from the messages.log

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#268]
To reduce the following warnings in message.log
- SRVE9967W: The manifest class path jaxb-api.jar can not be found in jar 

add `<scope>test</scope>` in the  following`<dependency/>` elements in the pom.xml
```
        <!-- Support for JDK 9 and above -->
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
```

Need to apply this change to the guides which pom.xml have the section of `<!-- Support for JDK 9 and above -->`

**Comment by justineechen** [comment]
Affected guides:

- [ ] guide-maven-multimodules
- [ ] guide-jpa-intro
- [ ] guide-microprofile-jwt
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-microprofile-opentracing
- [ ] guide-kubernetes-intro
- [ ] guide-kubernetes-microprofile-config
- [ ] guide-maven-intro
- [ ] guide-microprofile-rest-client
- [ ] guide-security-intro
- [ ] guide-microprofile-metrics
- [ ] guide-microprofile-openapi
- [ ] guide-microprofile-fallback
- [ ] guide-getting-started
- [ ] guide-cors
- [ ] guide-cdi-intro
- [ ] guide-rest-hateoas
- [ ] guide-bean-validation
- [ ] guide-microprofile-health
- [ ] guide-docker
- [ ] guide-rest-client-java
- [ ] guide-microprofile-config

**Comment by justineechen** [comment]
Checklist for issue:

- [ ] Clone guide and build project 
- [ ] Check for `SRVE9967W` in `target/liberty/wlp/usr/servers/defaultServer/logs`
- [ ] Remove the four dependencies for `JDK 9  & above` from the pom.xml
- [ ] Test guide's application and tests on JDK 8 and JDK 11
- [ ] If this fails, add the dependencies back with `<scope>test</scope>`. Otherwise, proceed 

- [ ] Check for `SRVE9967W` in `target/liberty/wlp/usr/servers/defaultServer/logs` and make sure it is not there anymore
- [ ] Run guide end to end checking on openliberty.io and check to see if there is any mention of pom.xml and if so, are any hotspots affected?
- [ ] If hotspots are affected, update `README.adoc` accordingly
- [ ] Update `start/pom.xml` if needed 
- [ ] Create PR
- [ ] Add PR card to wekan board
