### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guides-common#28]
We need feedback on these:

**Overall Layout**
There are two options for this one:

1\. Everything in-line. Explanations followed by blocks of code, followed by more explanations, etc. This is the current format of the guides.

2\. Have the code snippets, tables, output blocks, etc. flow on the right side of the page while the
explanations flow on the left side. Stripe does a very good job with this and it looks really neat: https://stripe.com/docs/api/curl#authentication 

Basically, every section will be separated from every other (personally I like the suggestion by Kin in this issue: https://github.com/OpenLiberty/openliberty.io/issues/92). Each section will be as long as its longest left (text) or right (code, tables, etc.) side. In other words, the left or right side will make up in length with empty space (see Stripe).

**Copy/no copy**
Sometimes its confusing as to what code needs to be copied to clipboard. Currently our solution is to tag snippets that don't need copying with the "no_copy" class, which prevents the user from copying the snippet when clicking it directly. Of course the users can still just select the snippets themselves. There needs to be a better distinction or all blocks should just be copyable.

Suggestions:
- Make all blocks copyable - as long as there are good descriptions, it should be clear what needs to be copied.
- Add some sort of visual aid (one sentences can be added to the "Getting started" section that says something like "blue snippets are important for building classes and must be copied, orange are not" -> can replace "blue" with an actual color block to clarity):
  - different background color for copyable vs non-copyable blocks (blueish background = copy, yellowish = no copy): https://imgur.com/a/32XCi, how it looks like on openliberty.io: https://imgur.com/a/0Y8td
  - different border color for copyable vs non-copyable blocks: https://imgur.com/a/YOQdC

Accessibility? (currently there is no way to tell either)

**Website**
- The section titles don't stand out enough. Look at Laraval for example: https://laravel.com/docs/5.5/authorization. There is a good amount of white space between each section header and also all h1 headers have a "#" next to them, making them stand out more. Actually, the suggestions in this issue are really nice: https://github.com/OpenLiberty/openliberty.io/issues/92
- The table of contents should be static; ie. not move when scrolling through the guide (I noticed that there is already an issue opened for this: https://github.com/OpenLiberty/openliberty.io/issues/90)

**Summary**
All in all, we need to address these quickly and update the template accordingly as this is holding us back from doing more guides atm. Also, the more guides we write and the more we hold off on these things, the more difficult it will be to change everything later. We already have 11 guides out, with 3 others finished and almost ready to go. Tweaking these alone will take a 2-3 days.

This is an issue summarizes the following issues:
- https://github.com/OpenLiberty/guides-common/issues/18
- https://github.com/OpenLiberty/guide-microprofile-intro/pull/34
- https://github.com/OpenLiberty/guides-common/issues/16

**Comment by Kubik42** [comment]
Please leave your feedback here (feel free to add your own text directly into the one above, just please make it italic or bold so it stands out)

**Comment by lauracowen** [comment]
In general, I think this is a good summary. 

I think the language point is moreorless agreed (though there'll always be specific questions to discuss). See the 'tone and voice' document for explanations about how to make technical documentation (this is technical documentation, we're just trying to have a more modern tone and voice to it) more conversational without losing its clarity and conciseness. So, for example, almost always use present tense (not because it's a rule per se but because, with a few exceptions, it makes the clearest, most concise technical writing), use contractions unless it reads awkwardly, and very sparingly use "let's" - if you're not sure, just don't use it. There aren't hard-and-fast rules to this kind of thing - often it's a case of how it reads which the author might not be able to tell without some distance from it. If anyone's struggling to know what's best, just do what you think and it'll get picked up during review and can be discussed further then. I think we have to accept that there will be some inconsistencies at a low level between guides in their language because they're written by different people. The main thing is that they are concise, meaningful, readable, usable, etc.

I think we should do away with the no_copy tag. Just have copy on everything and make the structure of the guides simpler so that it's obvious and not confusing.

I think it could be useful to have differentiation between commands (eg no grey background), code (eg a grey background and syntax highlighting), and console output (eg grey background and no syntax highlighting - which it wouldn't have). There'll be occasions where code doesn't show much syntax highlighting because of its content but I think that's enough.

I like the Stripe/Twilio page format but I think that definitely needs usability testing before we decide. Also, I'm not sure how well that would work with the 'cards' approach to the sections - don't want to end up with loads of gaps in the page - I think we need to decide the page format (code at the side vs code inline) first.

I agree with your point about the 'you're done' but there needs to be something at the end showing that it's the end of the guide. And while it's not functionally useful, it does give a sense that you've successfully finished and that the author cares. I don't think it's a problem to just keep this.

Thanks for writing all this up (I don't have any comments on anything I've not commented on. :) )

**Comment by yeekangc** [comment]
Thank you, @Kubik42.

@Kubik42 @evelinec:

For items where the answers are obvious, we can incorporate the proposed changes in a draft and take it forward for review and then close them out.

For items where there are options, let us work with work out the alternatives and prototype them with whomever appropriate and necessary, then take them forward for feedback from the community and user testing.

If necessary, we can prioritize the items in terms of impact and importance if they are too much to handle in one go.

**Comment by Kubik42** [comment]
We made a few of the decisions as a team already. These have been added to template.adoc. There is also a new section in the Wiki: https://github.com/OpenLiberty/guides-common/wiki/Rules-of-thumb for general formatting rules that must be followed when writing the guides.

**Comment by yeekangc** [comment]
Let us review and discuss those with the broader team before we commit, @Kubik42.

**Comment by Kubik42** [comment]
@yeekangc Of course. I created a PR for now: https://github.com/OpenLiberty/guides-common/pull/29

**Comment by Kubik42** [comment]
Addressed in cb8ccc48755f08f3184b0327633ca8d2af047e7a
