### ISSUE TITLE
Concern over code action arrow - UI

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guides-common#313]
There has been some discussion over the UI green arrow and how we word instructions in this arrow. 

@aguibert 

<img width="477" alt="Screen Shot 2019-06-25 at 11 58 38 AM" src="https://user-images.githubusercontent.com/18709242/60113915-bf9dc600-9740-11e9-8197-3134e2e7f702.png">

<img width="476" alt="Screen Shot 2019-06-25 at 11 58 27 AM" src="https://user-images.githubusercontent.com/18709242/60113914-bf9dc600-9740-11e9-8ef4-5865f2a2fefe.png">

**Comment by mbroz2** [comment]
Regard "File" vs "File Location" I'm largely impartial between the two so I went with the shorter one to help focus on the content instead of the heading (neither term is well, uniformly defined).

My preferred heading would actually be "Path:" since that's the most correct, widely accepted term, however, it implies (mandates really) that it's specific to the environment/OS which means that we'd want to make sure the delimiter matches the user's OS based on their user agent (similarly to what we do for some of the guides that have OS specific instructions).
Since this would take more work to implement, I'd rather go with File or File Location for now, and open a different issue if we want to pursue the above.
