### ISSUE TITLE
SEO: Guide webpages filtered out on Google search results in favor of Github repo

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/guides-common#373]
For certain search queries, the openliberty guide web page is being filtered out of google search results in favor of the Github repo page. For example, this occurs for the `openliberty arquillian` query:

<img width="626" alt="Screen Shot 2019-11-20 at 3 57 53 PM" src="https://user-images.githubusercontent.com/3202957/69281792-8c0b7e80-0bae-11ea-8b97-e758fe2d843e.png">

The result only appears if you turn off result filtering by appending `&filter=0` to the URL:

<img width="621" alt="Screen Shot 2019-11-20 at 4 00 59 PM" src="https://user-images.githubusercontent.com/3202957/69282027-f58b8d00-0bae-11ea-9eca-a64552e14974.png">

This is likely because Google believes the Github page to be the provider of the original content. One solution is to rename the default branch to something other than `master`, as according to this StackOverflow [post](https://stackoverflow.com/questions/15844905/how-to-stop-google-indexing-my-github-repository), the Github robots.txt only allows indexing of the `master` branch.

**Comment by yeekangc** [comment]
@lauracowen @mbroz2 @steven1046 @gkwan-ibm

**Comment by mbroz2** [comment]
Although the community expectation would be to have the branch name be master, since external committers don't interact with that branch I think it should be fine to rename it since it would only change internal/maintainer process, while giving our users better results in searches.  

(We should however keep in mind that this is only a google search problem and solution, as we get correct results for other search engines, and that google can change their search engine algorithm at any time to make it scan all branch names, in which case we'd again have this issue)

**Comment by steven1046** [comment]
For moving the master contents we will first need to branch a new branch off of master with the same contents, then update the build scripts to clone the new branch name, and then we can remove the contents in master.

**Comment by gkwan-ibm** [comment]
close
- all guides default branch were renamed to `prod`
