### ISSUE TITLE
Provide a direct way to access a guide's repo or sample project

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/guides-common#462]
On each guide's page, there isn't any direct link to the guide's GitHub repo.  "Fork the code" at the top goes to the OL repo, while the "Nice work! Where to next?" section has links to the issues and pull requests on the guide's repo.  But whenever I want to see the code for a guide, I need to click one of those links (e.g. issues page) then navigate to the Code tab on GitHub.  

Alternatively, instruction for cloning a repo is also provided in the guide, but if I just want to view the code without cloning it, I currently need to copy and paste GitHub repo URL from that text to view it in my browser.

Should there be an easier way to get to a guide's repo (or at least the `finish` sample project) without needing multiple clicks?

Additional context:
A guide provides two things: a tutorial, and sample project.  The guide page covers the former, but does not show a complete picture of the latter.  The right code pane is only in the context of the tutorial text (and specific to the section where you have scrolled to, e.g. files don't appear until after you scroll down to its section).    For someone looking for an overview of the sample project (project layout, how different parts fit together, how much code is involved in total (not just for going from start to finish)), there is no way to do so other than by going to the code, and GitHub is the natural way to view it quickly on a browser and even has code navigation.

**Comment by yeekangc** [comment]
@gkwan-ibm @mdenby, FYI.

**Comment by mdenby** [comment]
I'll also look at this today.

**Comment by mdenby** [comment]
What if we add a small snippet in the Getting Started section with "Or just view the finish sample project" with a link?

![Screen Shot 2020-06-08 at 2 38 49 PM](https://user-images.githubusercontent.com/26823018/84067797-fb538f00-a995-11ea-9521-5ad27ce54801.png)

**Comment by gkwan-ibm** [comment]
**Alternative 1:**
- made "Github repository" a link to the repo as the following screenshot, but it will point to the root directory instead of the finish directory
![Screen Shot 2020-06-08 at 4 18 27 PM](https://user-images.githubusercontent.com/29576299/84076481-cf3f0a80-a9a3-11ea-9a2e-68182c78fc4a.png)
- see `http://lgdev1.fyre.ibm.com:4060/guides/cdi-intro.html#getting-started`

**Alternative 2:**
- for the file displayed in the right pane, beside the copy button at the top, add another button/link to the exact file in the github repository. Of course, the README may need to be updated. 

**Note:**
- The display source files under finish directory in github repo usually contain hotspot tags, i.e. not easy to read from the repo, but read from the guide is nicer.

**Comment by yeekangc** [comment]
I lean toward something outside of the text itself atm.

@mbroz2 @lauracowen @aguibert, thoughts?

**Comment by mbroz2** [comment]
I like @gkwan-ibm Alternative 1.  It gives the user one of two choices: clone the repo or go view the files on github (just like @mdenby's proposal, which would work too, but places more emphasis on this option).  In other words, I like this approach because it de-emphasizes the link (the fact that it's easy & quick to implement is also a plus).
Regarding Alternative 2, since we already show the file in our guide, I think it feels redundant (it's the files we don't show in the guide that users would likely want to see, or the overall structure of the project).  If we wanted something like that (more prominent placement throughout the guide), then I'd recommend instead just having a single link to the root (or finish) directory, statically placed on the right/code pane (perhaps a github logo docked/stickied to the bottom right service as the link/button).

**Comment by aguibert** [comment]
+1 for Alternative 1. Having a simple hyperlink to the github repo gets the job done.

**Comment by lauracowen** [comment]
I'd be ok with Alternative 1. But I've frequently gone looking for a link to the GitHub repo at the bottom of the ToC where the tags are. I don't know why I expect it to be there (maybe that's similar to where Spring put theirs) but that suggests it may be a natural place to put it (though obvs not everyone has the ToC expanded).

**Comment by yeekangc** [comment]
Yes, Alternative 1 is alright (though if you are elsewhere in the guide, you will have to remember/know the link is there and scroll back up to find it.)

IIRC, @ericglau commented that folks may confuse the "Fork the Code" button in banner to mean taking them to the repo for the guide instead of Open Liberty instead.

In a similar vein, as Laura noted, I wonder if users will scroll down or look for a link at the ToC bar.

**Comment by gkwan-ibm** [comment]
Let fix with Alternative 1 first. https://github.com/OpenLiberty/openliberty.io/issues/1694 will address following by UI:
- Readers may confuse that the "Fork the Code" button in banner to mean taking them to the repo for the guide instead of Open Liberty instead.
- provide an easy/obvious way to allow jump to the guide repo without the need scroll back to the Getting started section where will provide a link to the guide repo (Alternative 1)

**Comment by gkwan-ibm** [comment]
close
- all guides are using  Alternative 1
