### ISSUE TITLE
Guide for Arquillian Managed

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/guides-common#53]
Guide on how to use the `configureArquillian` task in `liberty-gradle-plugin` and `configure-arquillian` goal in `liberty-maven-plugin`, as well as the Arquillian Liberty dependency bundles, with Arquillian Liberty Managed 1.0.0.Final (pending release).

**Comment by yeekangc** [comment]
This is the case where Arquillian will work with a Liberty server that is local.  It will cover both Maven and Gradle.

**Comment by yeekangc** [comment]
Draft repo: https://github.com/OpenLiberty/draft-guide-arquillian-managed

**Comment by gkwan-ibm** [comment]
- working on the comments
- reworking the java code and the guide

**Comment by gkwan-ibm** [comment]
- met Charles to get better understanding and the focus
- working on the guide
   - more explanation
   - style
   - make sure that the license agreement should be good
   - etc.
- Gilbert need to discuss with YK about the content

**Comment by gkwan-ibm** [comment]
- addressed most of the comments
- addressing the rest comments
- study how to use arquillian to test microservice application

**Comment by gkwan-ibm** [comment]
- the focus is to work out/prototype how to use arquilian to test the microservcie application

**Comment by gkwan-ibm** [comment]
- objective is to make the regular endpiont can coexist with Arquillian test by managed container

**Comment by gkwan-ibm** [comment]
- proved that both the regular endpiont and Arquillian tests can coexist but they run in parallel
- will try Arquillian client to do endpoint test

**Comment by evelinec** [comment]
- Fixed the client test case for testing the URL
- Will implement the both test cases on a more involved service to demo arquillian benefits

**Comment by gkwan-ibm** [comment]
- enhancing the microservice and tests

**Comment by gkwan-ibm** [comment]
- working on the application and tests
- working on the Readme
- target to complete on next week and be published on next iteration

**Comment by evelinec** [comment]
- guide's outline is ready for review
- working on the remaining test cases and draft

**Comment by gkwan-ibm** [comment]
- code is available in the branch fixingfeedback
- working on the readme
- required ID to review in this iteration

**Comment by gkwan-ibm** [comment]
- all changes in master branch 
- will be available in the staging site
- will review with Charles

**Comment by gkwan-ibm** [comment]
- chatted with Charles
- addressing his suggestion
- will meet with Charles

**Comment by gkwan-ibm** [comment]
- Gilbert will study more about Arquillian

**Comment by gkwan-ibm** [comment]
- Gilbert updated the pom.xml and server.xml the apps
- Readme will be rewritten

**Comment by evelinec** [comment]
- Will start addressing the review feedback

**Comment by gkwan-ibm** [comment]
- addressing feedback
- no pom.xml in Readme
- no gradle and open a backlog issue
- target: Jan 17

**Comment by gkwan-ibm** [comment]
- Asked Charles to do SME review

**Comment by gkwan-ibm** [comment]
- addressed SME and peer review feedback
- SME and Peer reviewers will confirm the changes
- User review can be performed on today

**Comment by gkwan-ibm** [comment]
- addressed  new SME feedback
- did Arcolinx check
- User review is in progress
- YK is reviewing

**Comment by gkwan-ibm** [comment]
@yeekangc 

Readiness checklist
- [x] Development
- [x] Content Review - Gilbert
- [x] Peer Review - Andrew
- [x] SME Review - Charles
- [ ] User Review - Rachel
- [ ] Signoff Review - YK

**Comment by yeekangc** [comment]
Thank you, @gkwan-ibm.  Looks like we still need User Review before we can do Signoff Review now (today) to make this (Jan) cycle.

**Comment by evelinec** [comment]
- user review had been done
- YK is reviewing

**Comment by evelinec** [comment]
- working on addressing Laura's feedback

**Comment by gkwan-ibm** [comment]
- addressed the Laura's feedback

**Comment by gkwan-ibm** [comment]
- requested YK and Laura to review
- conversing to multipane

**Comment by gkwan-ibm** [comment]
- converted to multipane

**Comment by gkwan-ibm** [comment]
- need to have User Review again because converted to multipane

**Comment by gkwan-ibm** [comment]
- Tommy and Justine did the user review for multipane

**Comment by gkwan-ibm** [comment]
- addressing YK's feedback

**Comment by gkwan-ibm** [comment]
- addressed most YK's feedback
   - Gilbert will review the PR

**Comment by gkwan-ibm** [comment]
- will address Gilbert's feedback in the PR

**Comment by gkwan-ibm** [comment]
- addressed the feedback
- the guide was updated in the qa-multipane site
- Gilbert and YK will review again

**Comment by gkwan-ibm** [comment]
- waiting YK review

**Comment by yeekangc** [comment]
@gkwan-ibm @evelinec, can you please post an updated readiness checklist for the multi-pane version?

**Comment by evelinec** [comment]
- waiting for YK's text editing PR before ID review

**Comment by evelinec** [comment]
@chirp1 This guide is ready for you to review. Here's the repo: https://github.com/OpenLiberty/draft-guide-arquillian-managed. Thank you.

**Comment by chirp1** [comment]
Hi!
Here are my review comments for the guide. If you have any questions, feel free to sametime me or slack me.

Global change: Make sure that you are using the name of the container consistently. You might be referring to two containers, the more general "Arquillian managed container" and the Liberty version of the container-  the "Arquillan Liberty managed container". If they are two different containers, then make sure that you use their names consistently. If it is one container, then use the same name throughout the guide. In some cases "Managed" is capitalized in the guide. Use lower case instead. 

Change the title of  "Testing microservices with Arquillian managed container" to "Testing microservices with the Arquillian managed container".

Change "microservices using the" to "microservices by using the".

Change ".... and is able to handle the application server lifecycle for you, so you can focus on writing tests." to "... and handles the application server lifecycle for you so that you can focus on writing tests.".

Change "In this guide, you will develop Arquillian tests that use JUnit as the runner and build your tests with Maven using the Liberty Maven plug-in, which simplifies the process of managing Arquillian dependencies and the setup of your Arquillian managed container. 

Change "In this guide, you will develop Arquillian tests that use JUnit as the runner and build your tests with Maven using the Liberty Maven plug-in, which simplifies the process of managing Arquillian dependencies and the setup of your Arquillian managed container. " to "You will develop Arquillian tests that use JUnit as the runner and build your tests with Maven by using the Liberty Maven plug-in. This plug-in simplifies the process of managing Arquillian dependencies and the setup of your Arquillian managed container. ".

Change "The application that you will work with is an inventory service that stores information about various systems. " to "You will work with an inventory service application, which stores information about various systems. ".

Change "and stores them. " to "and store them. ".

Change "You will also learn about the Maven and server configurations you need to run your tests " to "You will also learn about Maven and server configurations so that you can run your tests ".

Change "To try running the finished " to "To run the finished ".

Change "You should see the console output indicating that your build is successful and the tests have passed. " to "In the console output, search for an indication that the build was succesful and that the tests passed. ".

Change "The code for the microservices is provided to you under the " to "The code for the microservices is in the ".

Change "Navigate to the start directory to begin.
Create the InventoryArquillianTests test class." by first moving "Create the InventoryArquillianTests test class" out of the highlighted area. Then change the wording to "In the start directory, create the InventoryArquillianTests test class.".

Change "Notice the JUnit Arquillian runner is being used to run the tests, instead of the standard JUnit runner. The @RunWith annotation at the top of the class tells JUnit to run the tests using Arquillian." to "Notice that the JUnit Arquillian runner runs the tests instead of the standard JUnit runner. The @RunWith annotation preceding the class tells JUnit to run the tests by using Arquillian.".

Change "The testable = true attribute enables the deployment to run the tests "in container", that is the tests are run on the server." to "The testable = true attribute enables the deployment to run the tests on the server.".  

Change "name used for the web archive. " to "name that is used for the web archive. "

Change "This is necessary if " to "This name is necessary if ".

For "ShrinkWrap is used to create..." we want to say what ShrinkWrap is. From reading the paragraph and going out to the web, how about if we start it with "The ShrinkWrap archive configuration is used to....". Or might if some other noun should follow "ShrinkWrap", for instance "class", then use that noun instead.

Change ".... the client side, which means the tests are run against the managed container." to "....the client side. By running the tests on the client side, the tests are run against the managed container. ".

Change "The test checks that the inventory should have one host and that should be localhost." to "The test checks that the inventory has one host and that the host is localhost.".

How about if we split the paragraph starting with "Contexts and Dependency Injection (CDI) is used ..." into two paragraphs. So for, the first paragraph, keep "Contexts and Dependency Injection (CDI) is used to inject an instance of the InventoryResource class into this test class. You can learn more about CDI in the Injecting dependencies into microservices guide.". 

For the second paragraph, let's change the first sentence a little. Change "The instance is then tested by the ..." to "The InventoryResource instance is tested by the...."

Change "...method to get all systems are stored in... " to "...method to get all systems that are stored in...". 

Change "by configuring the server.xml. " to "by configuring the server.xml file.".

The meansing for "Using JUnit" is a bit ambiguous.  I believe what is meant is "that uses JUnit." However, possibley, "by using JUnit" was meant. Change the wording to the correct wording. For instance, change "...Arquillian tests on a managed Liberty container using JUnit." to "....Arquillian tests on a managed Liberty container that uses JUnit.".  

Move "You can learn more about the Arquillian Liberty dependency bundles." to the end of the paragraph.

Change "your test archive which is packaged" to "your test archive, which is packaged". (Add a comma.)

Change "The maven-failsafe-plugin runs your Arquillian integration tests using JUnit. " to "The maven-failsafe-plugin artifact runs your Arquillian integration tests that use JUnit. ". (or "by using JUnit, as appropriate)

Change "You can learn more about the configure-arquillian goal in its documentation." to "You can learn more about the configure-arquillian goal.".  <= make "configure-arquillian goal" the link.

For ".... the skipTestServer element is set to true to skip....", highlight "true" like you have highlighted other text since "true" is a value.

Change "Also, notice in..." to "Notice in...".

Change the title of "Configuring the server.xml" to "Configuring the server.xml file".

Change "Maven build, setup your " to "Maven build, set up your ".

Change "you see the application server was launched, and the web archive, archive, arquillian-managed, is started as an application in the server." to "you can see that the application server launched, and that the web archive, arquillian-managed, started as an application in the server. ". <= Add "that" twice.

Change "Then, the tests are being run and the results are reported." to "You can also see that tests are running and that results are reported.".

Change "Following the execution of the tests, the test application is automatically undeployed and the server is shut down." to "After the tests stop running, the test application is automatically undeployed and the server shuts down.".

Change "You have just built..." to "You just built ...".

Change ...with the Arquillian Liberty Managed container..." to "...with the Arquillian Liberty managed container ..." or   "...with the Arquillian managed container ...".

Change "You can continue to try one of the related guides..." to "Try one of the related guides...".

**Comment by evelinec** [comment]
Guide is published: https://openliberty.io/guides/arquillian-managed.html
