### ISSUE TITLE
Update guides that use Docker images to pull from icr.io

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#712]
Docker Hub has a rate limits.  Open Liberty images are now available on icr.io (IBM Container Registry) without authentication required.  No rate limits for ICR.

FROM icr.io/appcafe/open-liberty

Update guides to use icr.io going forward to avoid rate limit issues.

![image (22)](https://user-images.githubusercontent.com/4803104/134406183-8a2f23dd-af50-4b48-be08-a66b0116287c.png)

**Comment by yeekangc** [comment]
@gkwan-ibm, can you please consider?  Let us discuss and we can prioritize accordingly.

**Comment by gkwan-ibm** [comment]
tried` icr.io/appcafe/open-liberty:full-java11-openj9-ubi`. It works. If change to use it, need to do following:
- guides-common
  - update 3 ol-*-docker-pull.adoc files
- guides that using docker
  - look for any change for README
  - update Dockerfile
  - update test scripts
- update analytics

Questions:
- Need to claim which repository should be used for production?

**Comment by gkwan-ibm** [comment]
@yeekangc 
it is ok to close
- most guides were updated except the following:
  - the guide-cloud-openshift will be deprecated because of using openshift 3
  - the guide-cloud-google will be addressed by https://github.com/OpenLiberty/guide-cloud-google/issues/46
  - the guide-okd will be addressed by https://github.com/OpenLiberty/guide-okd/issues/84
