### ISSUE TITLE
Consider pre-creating files or directories under /start

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#87]
Currently, we ask users to create new files themselves and then add the code or content.  This can be a hassle for users especially if they have to do so multiple times.  Or, if they aren't familiar with the necessary commands or tools to do so.

We should seek to improve the experience and consider pre-creating such files under /start so users can focus on the content and code.

**Comment by lauracowen** [comment]
Some of the more recent guides provide the directory structure with a `.gitkeep` file in it so that GitHub retains the structure without any files in it. After brief discussion, agreed with @NottyCode @yeekangc @gcharters @kwsutter that we should do this for all guides. No placeholder java files etc; just the empty directory structures with `.gitkeep` files as necessary. This means that developers are actively involved in creating the files in the correct directories as part of the learning process but they don't need to do the irritating and easily-error-prone part of creating the directory structure too.

**Comment by evelinec** [comment]
We have already been doing what @lauracowen described for the recent guides. @proubatsis can you review all published guides and see any of them need to have the directory structure created. Thanks.

**Comment by evelinec** [comment]
@yeekangc By pre-creating files, do you mean to create an empty file with the class names and let user paste the contents in the files? Are we decided to go about doing this? Thanks.

**Comment by proubatsis** [comment]
@evelinec
https://github.com/OpenLiberty/guide-rest-client-java/pull/19
https://github.com/OpenLiberty/guide-rest-client-angularjs/pull/21
https://github.com/OpenLiberty/guide-rest-intro/pull/34
https://github.com/OpenLiberty/guide-rest-hateoas/pull/26

**Comment by evelinec** [comment]
@proubatsis I believe this is resolved already?
