### ISSUE TITLE
Create a guide for Open Liberty with Istio

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guides-common#99]

**Comment by yeekangc** [comment]
https://github.com/OpenLiberty/draft-guide-kubernetes

**Comment by proubatsis** [comment]
@gcharters @yeekangc What specific features of Istio should be covered in this guide? Is it up to me to decide, or do either of you have any preference?

**Comment by evelinec** [comment]
- fixing the code

**Comment by gkwan-ibm** [comment]
- the app is broken and fixing

**Comment by gkwan-ibm** [comment]
- proved that Mac works fine
- investigating Linux why minikube crashed at the end
- updating the Readme

**Comment by gkwan-ibm** [comment]
- Linux issue was resolved
- investigating BlueGreen deployment

**Comment by gkwan-ibm** [comment]
- wrote new app for blue-green deployment

**Comment by evelinec** [comment]
- app, test, readme are all ready
- can start peer review (Andrew to do this afternoon)

**Comment by gkwan-ibm** [comment]
- addressing Andrew's comments
- did Mac, and will do Windows and Linux

**Comment by gkwan-ibm** [comment]
- finished to test all 3 platforms
- Fixes will be merged soon
- Content and then SME review

**Comment by gkwan-ibm** [comment]
- Gilbert gave some feedback and will be addressed on today

**Comment by gkwan-ibm** [comment]
- working on  feedback for Windows

**Comment by gkwan-ibm** [comment]
- YK is reviewing
- Ask for SME review

**Comment by gkwan-ibm** [comment]
- YK reviewed 
- will review by SME

**Comment by gkwan-ibm** [comment]
- addressing SME review
- confirm the title and description
- should start User view: Win and Unbanto 
- target Jan 17: all development works including SME, User etc

**Comment by gkwan-ibm** [comment]
- addressing SME review
- Tommy (Ubanto) and Justine (Win) will do user review on today

**Comment by gkwan-ibm** [comment]
- addressing Win (Justine) feedback
- Ubuntu (Tommy) is reviewing

**Comment by gkwan-ibm** [comment]
- all development works were completed including user review

**Comment by gkwan-ibm** [comment]
Readiness checklist
- [x] Development
- [x] Content Review - Gilbert
- [x] Peer Review - Andrew
- [x] SME Review - Emily and Vadim
- [x] User Review - Tommy and Justine
- [ ] Signoff Review - YK

@yeekangc

**Comment by yeekangc** [comment]
We have all pieces ready.  Moving forward with signoff review.  Thank you.

**Comment by evelinec** [comment]
- working on feedback from YK, have PR ready today
- ID review to be arranged

**Comment by evelinec** [comment]
- pre and post tests (on Linux and Mac)

**Comment by evelinec** [comment]
Post-Publishing Tests

- [ ] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [ ] Clone repo and test finish directory with no error
- [ ] Add description for the repo with link to guide's published website
- [ ] Enable pull creation notification on the repo

**Comment by gkwan-ibm** [comment]
publishing
- [ ] rename to guide-istio-intro

**Comment by chirp1** [comment]
Hi! 
Here are my review comments for the guide. If you have any questions, sametime me or slack me.

Global change: Change "testing environment" to "test environment". Also, anytime you use "testing' as and adjective in front of a noun, such as 'testing traffic", change it to "test", i.e. "test traffic".

- Change "You can think of Envoy as a sidecar that intercepts and controls all the traffic to and from your container, it deals with HTTP and TCP traffic." to "You can think of Envoy as a sidecar that intercepts and controls all the HTTP and TCP traffic to and from your container."

- Change "note that Istio can also be used with other environments such as Docker Compose." to "you can also use Istio with other environments such as Docker Compose." <= also, how about making "Docker compose" a link?

Change "One example is Istio’s routing features, it allows you to route HTTP requests based on several factors such as HTTP headers or cookies. " to "One example is Istio’s routing features. You can route HTTP requests....".


Change "... Telemetry, which can be used to enable.... " to "...telemetry, which you can use to enable.... ".

Change "...services in your cluster using a tool ..." to "...services in your cluster by using a tool...".

Change "Finally, one of the items Istio offers under its collection of security features is to enable mutual TLS between pods in your cluster. " to "Additionally, as part of its collecxtion of security features, Istio allows you to enable mutual TLS between pods in your cluster.".

Change "Enabling HTTPS between pods..." to "Enabling TLS between pods...".
 
Can you change "blue-green deployments" so that it is a link to "What are blue-green deployments?" ?

Chanage "The traffic shifting features allows...." to "The traffic shifting feature allows...". (Remove the "s" from "features".)

Change "This feature can be used to shift..." to "You can use this feature to shift ...".

Change "deployments as is necessary" to "deployments as necessary ".

Change "In this scenario, there will be a production environment " to "In this scenario, you will have a production environment ".

Change "At any point in time the blue deployment may be accepting production traffic and the green accepting testing traffic or vice-versa. " to "At any point in time, the blue deployment can accept production traffic and the green deployment can accept test traffic, or vice-versa. ". 

Change "Once the new version..." to "After the new version...".

Change "Before you begin, make sure to have.." to "Before you begin, have...".

Change "First, you will need a containerization software..." to "First, you will need containerization software...". (Remove "a".)

Add a comma after "If you do not see the Kubernetes tab".

Before "Set up Docker for Windows. ", add a one sentence paragraph: "Complete the setup for your operating system:".

Add a comma after "For Minikube installation instructions".

Change "Make sure to read the Requirements..." to "Read the Requirements...".

Change "finished project, which is what you will build. " to "finished project that you will build. ".

Change "Start up your Kubernetes cluster." to "Start your Kubernetes cluster.".

Change "This should return..." to "This command should return ...".

Change "After running this command, " to "After you run this command, ".

Change "Next, deploy Istio’s resources..." to "Next, deploy Istio resources ...".

Change "...value of 1 once.... " to "...value of 1 after... ".

Change "Ensure that the Istio deployments are all available before continuing, it may take a few minutes for all of them to be available." to "Ensure that the Istio deployments are all available before you continue. The deployments might take a few minutes to become available.".

Change "On Docker Desktop, this can be done from your Docker preferences." to "On Docker Desktop, you can do the increase from your Docker preferences.". 

Change "On Minikube, this can be done using the --memory flag. " to "On Minikube, you can do the increase by adding the --memory flag. ". 

Change "After running the command, it builds..." to "The command builds...".

Change "by running the given command. " to "by running the following command. ".

Change "You’ll see an image called hello:1.0-SNAPSHOT listed in a table similar to the output. " to "You’ll see an image with a repository name of hello and a tag of 1.0-SNAPSHOT listed in a table similar to the following output. ".

Change "use kubectl to deploy " to "use the following command to deploy ".

Change "the weights should be 100 or 0 which corresponds " to "the weights are 100 or 0, which corresponds ".

Change "...defined in traffic.yaml." to "...defined in the traffic.yaml file.".

Change "deployments are available using the command. " to "deployments are available by running the following command. "

Change "Which produces a list of deployments for your microservices. " to "The command produces a list of deployments for your microservices that is similar to the follwoing output."

Change "Once all the deployments " to "After all the deployments ".

Change "As defined in hello.yaml " to "As defined in the hello.yaml file. ".

Change "Requests to " to "However, requests to".

Change "Ensure that the Host header is set to example.com so the gateway routes your requests appropriately, for instance, with the -H option of the curl command. " to "To ensure that the gateway routes your requests appropriately, ensure that the Host header is set to example.com. For instance, you can set the Host header with the -H option of the curl command. ".

Change "by using curl." to "by running the follow curl command.".

Change "If curl is unavailable, " to "If the curl command is unavailable, ".


Change "with key Host and value example.com " to "with a key of Host and a value of example.com ".

Change "by using curl." to "by running the follow curl command.".

Change "and it is still 1.0-SNAPSHOT " to "and is still 1.0-SNAPSHOT ".

Change "by using curl." to "by running the follow curl command.". <= comment for Windows/Mac
Change "If curl is unavailable, " to "If the curl command is unavailable, ".

Change "by using curl." to "by running the follow curl command.". <= comment for Linux

Change "Once you see " to "After you see ".

Change "by using curl." to "by running the follow curl command.". <= comment for Windows/Mac
Change "If curl is unavailable, " to "If the curl command is unavailable, ".

Change "by using curl." to "by running the follow curl command.". <= comment for Linux

Change "output similar to the following: " to " output similar to the following example: ".

Change "Finally, you may want to teardown " to "You might want to teardown ".

Change "Perform the following two steps " to "Perform the following steps ".
 
Number the steps 1, 2, and 3.
Change "Firstly, point " to "1. Point".
Change "Then, stop " to "2. Stop".
Change "Finally, delete " to "3. Delete".

Change "You have deployed a microservice running on Open Liberty " to "You have deployed a microservice that runs on Open Liberty ".

**Comment by gkwan-ibm** [comment]
Publish (Gilbert)
- [x] update the publish date
- [x] rename the guide repo
- [x] add the guide url in the GitHub repo description
- [x] refresh master

**Comment by justineechen** [comment]
Post-test on Linux (Justine)
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [x] Clone repo and follow the instruction in the guide to test the guide
